# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd9PZsGeaQAtCLzZm4isgJcjGsSTwrC5

#SARS CoV 2 sc-RNA-seq Analysis
## Overview
This notebook constitutes the first deliverable of the SARS-CoV-2 Infection Dynamics project. It focuses on preprocessing the single-cell RNA sequencing (scRNA-seq) data obtained from the study by *Ravindra et al., 2021 (PLOS Biology)*. The aim is to prepare high-quality, normalized data for subsequent analyses  including neighbourhood clustering, cell type identification, and pseudotime trajectory inference.

In this stage, we will:

1.Load raw scRNA-seq count matrices.

2.Perform quality control  (QC) to remove low-quality cells and genes.

3.Normalize and transform the expression data.

4.Annotate metadata (infection condition, sample time points, etc.).

5.Save a clean .h5ad file for downstream analysis.

## Install Packages
"""

# Create environment by installing packages
!pip install scanpy
!pip install anndata
!pip install celltypist
!pip install decoupler
!pip install fa2-modified
!pip install scvelo
!pip install igraph
!pip install scikit-misc

"""## A. Preprocessing

### 01. Unzipping and Loading Datasets
"""

import tarfile
import os

!tar -xvf "/content/GSE166766_RAW (5).tar" -C "/content/Extracted files"     #[run this cell to extract tar.gz files]

# Import datasets
import scanpy as sc
import scvelo as scv
import anndata as ad
import numpy as np
import shutil

!pwd

#Import and load  datasets
mock_adata = sc.read_10x_mtx('/content/mock/')
srv_1dpi_adata = sc.read_10x_mtx('/content/1dpi/')
srv_2dpi_adata = sc.read_10x_mtx('/content/2dpi/')
srv_3dpi_adata = sc.read_10x_mtx('/content/3dpi/')

#Add metadata to track which condition this sample belongs to
mock_adata.obs['condition'] = 'mock'
srv_1dpi_adata.obs['condition'] = '1dpi'
srv_2dpi_adata.obs['condition'] = '2dpi'
srv_3dpi_adata.obs['condition'] = '3dpi'

"""### 02. Data Inspection
##### Checking important metrics
"""

print(mock_adata)
print(srv_1dpi_adata)
print(srv_2dpi_adata)
print(srv_3dpi_adata)

adata_list = [mock_adata, srv_1dpi_adata, srv_2dpi_adata, srv_3dpi_adata]
adata = ad.concat(adata_list)

adata

mock_adata.var.head()
srv_1dpi_adata.var.head()
srv_2dpi_adata.var.head()
srv_3dpi_adata.var.head()

"""### 03.  Quality Control (QC)

##### 3.1. Compute quality control metrics
"""

# Basic QC before filtering

## -- Identification of low-quality or dying cells

#mock dataset
mock_adata.var["MT"] = mock_adata.var_names.str.startswith("MT-")
mock_adata.var["RIBO"] = mock_adata.var_names.str.startswith(("RPS","RPL"))
mock_adata.var["HB"] = mock_adata.var_names.str.contains(("^HB[^(P)]"))
sc.pp.calculate_qc_metrics(
    mock_adata,qc_vars=["MT", 'RIBO', 'HB'], inplace=True, log1p=True
)

#1dpi dataset
srv_1dpi_adata.var["MT"] = srv_1dpi_adata.var_names.str.startswith("MT-")
srv_1dpi_adata.var["RIBO"] = srv_1dpi_adata.var_names.str.startswith(("RPS","RPL"))
srv_1dpi_adata.var["HB"] = srv_1dpi_adata.var_names.str.contains(("^HB[^(P)]"))
sc.pp.calculate_qc_metrics(
    srv_1dpi_adata,qc_vars=["MT", 'RIBO', 'HB'], inplace=True, log1p=True
)

#2dpi dataset
srv_2dpi_adata.var["MT"] = srv_2dpi_adata.var_names.str.startswith("MT-")
srv_2dpi_adata.var["RIBO"] = srv_2dpi_adata.var_names.str.startswith(("RPS","RPL"))
srv_2dpi_adata.var["HB"] = srv_2dpi_adata.var_names.str.contains(("^HB[^(P)]"))
sc.pp.calculate_qc_metrics(
    srv_2dpi_adata,qc_vars=["MT", 'RIBO', 'HB'], inplace=True, log1p=True
)

#3dpi dataset
srv_3dpi_adata.var["MT"] = srv_3dpi_adata.var_names.str.startswith("MT-")
srv_3dpi_adata.var["RIBO"] = srv_3dpi_adata.var_names.str.startswith(("RPS","RPL"))
srv_3dpi_adata.var["HB"] = srv_3dpi_adata.var_names.str.contains(("^HB[^(P)]"))
sc.pp.calculate_qc_metrics(
    srv_3dpi_adata,qc_vars=["MT", 'RIBO', 'HB'], inplace=True, log1p=True
)

import matplotlib.pyplot as plt
import seaborn as sns

# --- Visualize distributions before filtering ---
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
sns.histplot(mock_adata.obs['n_genes_by_counts'], bins=50, ax=axes[0], color='skyblue')
axes[0].set_title('Number of Genes per Cell (before filter)')
axes[0].set_xlabel('n_genes_by_counts')

sns.histplot(mock_adata.obs['total_counts'], bins=50, ax=axes[1], color='lightgreen')
axes[1].set_title('Total Counts per Cell (before filter)')
axes[1].set_xlabel('total_counts')

sns.histplot(mock_adata.obs['pct_counts_MT'], bins=50, ax=axes[2], color='salmon')
axes[2].set_title('% Mitochondrial Genes (before filter)')
axes[2].set_xlabel('pct_counts_mt')

plt.tight_layout()
plt.show()

# --- Visualize distributions before filtering ---
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
sns.histplot(srv_1dpi_adata.obs['n_genes_by_counts'], bins=50, ax=axes[0], color='skyblue')
axes[0].set_title('Number of Genes per Cell (before filter)')
axes[0].set_xlabel('n_genes_by_counts')

sns.histplot(srv_1dpi_adata.obs['total_counts'], bins=50, ax=axes[1], color='lightgreen')
axes[1].set_title('Total Counts per Cell (before filter)')
axes[1].set_xlabel('total_counts')

sns.histplot(srv_1dpi_adata.obs['pct_counts_MT'], bins=50, ax=axes[2], color='salmon')
axes[2].set_title('% Mitochondrial Genes (before filter)')
axes[2].set_xlabel('pct_counts_mt')

plt.tight_layout()
plt.show()

# --- Visualize distributions before filtering ---
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
sns.histplot(srv_2dpi_adata.obs['n_genes_by_counts'], bins=50, ax=axes[0], color='skyblue')
axes[0].set_title('Number of Genes per Cell (before filter)')
axes[0].set_xlabel('n_genes_by_counts')

sns.histplot(srv_2dpi_adata.obs['total_counts'], bins=50, ax=axes[1], color='lightgreen')
axes[1].set_title('Total Counts per Cell (before filter)')
axes[1].set_xlabel('total_counts')

sns.histplot(srv_2dpi_adata.obs['pct_counts_MT'], bins=50, ax=axes[2], color='salmon')
axes[2].set_title('% Mitochondrial Genes (before filter)')
axes[2].set_xlabel('pct_counts_mt')

plt.tight_layout()
plt.show()

# --- Visualize distributions before filtering ---
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
sns.histplot(srv_3dpi_adata.obs['n_genes_by_counts'], bins=50, ax=axes[0], color='skyblue')
axes[0].set_title('Number of Genes per Cell (before filter)')
axes[0].set_xlabel('n_genes_by_counts')

sns.histplot(srv_3dpi_adata.obs['total_counts'], bins=50, ax=axes[1], color='lightgreen')
axes[1].set_title('Total Counts per Cell (before filter)')
axes[1].set_xlabel('total_counts')

sns.histplot(srv_3dpi_adata.obs['pct_counts_MT'], bins=50, ax=axes[2], color='salmon')
axes[2].set_title('% Mitochondrial Genes (before filter)')
axes[2].set_xlabel('pct_counts_mt')

plt.tight_layout()
plt.show()

"""##### 3.2. Visualize before filtering"""

# Commented out IPython magic to ensure Python compatibility.
# Plot style setup for visual consistency
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (5,4)  # Adjust figure size
plt.rcParams["axes.grid"] = True  # Add grid to plots
plt.rcParams["axes.edgecolor"] = "black" # Set plot border color
plt.rcParams["axes.linewidth"] = 1.5 # Set plot border width
plt.rcParams["axes.facecolor"] = "white" # Set background color
plt.rcParams["axes.labelcolor"] = "black" # Set label color
plt.rcParams["xtick.color"] = "black" # Set x-axis tick color
plt.rcParams["ytick.color"] = "black" # Set y-axis tick color
plt.rcParams["text.color"] = "black" # Set text color
# %matplotlib inline

#Violin plots

#mock dataset
sc.pl.violin(
    mock_adata,
    ["n_genes_by_counts", 'total_counts', 'pct_counts_MT'],
    jitter=0.4,
    multi_panel=False,
)

#1dpi dataset
sc.pl.violin(
    srv_1dpi_adata,
    ["n_genes_by_counts", 'total_counts', 'pct_counts_MT'],
    jitter=0.4,
    multi_panel=False,
)

#2dpi dataset
sc.pl.violin(
    srv_2dpi_adata,
    ["n_genes_by_counts", 'total_counts', 'pct_counts_MT'],
    jitter=0.4,
    multi_panel=False,
)

#3dpi dataset
sc.pl.violin(
    srv_3dpi_adata,
    ["n_genes_by_counts", 'total_counts', 'pct_counts_MT'],
    jitter=0.4,
    multi_panel=False,
)

# Scatter plot of MT genes

#mock
sc.pl.scatter(mock_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

#1dpi
sc.pl.scatter(srv_1dpi_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

#2dpi
sc.pl.scatter(srv_2dpi_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

#3dpi
sc.pl.scatter(srv_3dpi_adata, "total_counts", "n_genes_by_counts", color="pct_counts_MT")

# filter for percent mito
mock_adata = mock_adata[mock_adata.obs['pct_counts_MT'] < 10, :]

srv_1dpi_adata = srv_1dpi_adata[srv_1dpi_adata.obs['pct_counts_MT'] < 10, :]

srv_2dpi_adata = srv_2dpi_adata[srv_2dpi_adata.obs['pct_counts_MT'] < 10, :]

srv_3dpi_adata = srv_3dpi_adata[srv_3dpi_adata.obs['pct_counts_MT'] < 10, :]

"""##### 3.2. Normalize and transform."""

# Normalize counts per cell to 10,000

#mock dataset
mock_adata.layers["counts"] = mock_adata.X.copy()
sc.pp.normalize_total(mock_adata)
sc.pp.log1p(mock_adata)  # log normalization

#1dpi
srv_1dpi_adata.layers["counts"] = srv_1dpi_adata.X.copy()
sc.pp.normalize_total(srv_1dpi_adata)
sc.pp.log1p(srv_1dpi_adata)  # log normalization

#2dpi
srv_2dpi_adata.layers["counts"] = srv_2dpi_adata.X.copy()
sc.pp.normalize_total(srv_2dpi_adata)
sc.pp.log1p(srv_2dpi_adata)  # log normalization

#3dpi
srv_3dpi_adata.layers["counts"] = srv_3dpi_adata.X.copy()
sc.pp.normalize_total(srv_3dpi_adata)
sc.pp.log1p(srv_3dpi_adata) # log normalization

#feature selection
sc.pp.highly_variable_genes(mock_adata, n_top_genes=1000)
sc.pl.highly_variable_genes(mock_adata)

sc.pp.highly_variable_genes(srv_1dpi_adata, n_top_genes=1000)
sc.pl.highly_variable_genes(srv_1dpi_adata)

sc.pp.highly_variable_genes(srv_2dpi_adata, n_top_genes=1000)
sc.pl.highly_variable_genes(srv_2dpi_adata)

sc.pp.highly_variable_genes(srv_3dpi_adata, n_top_genes=1000)
sc.pl.highly_variable_genes(srv_3dpi_adata)

"""## B. Dimensionality Reduction

#### 01. PCA
"""

#Dim Reduction
sc.tl.pca(mock_adata)

sc.tl.pca(srv_1dpi_adata)

sc.tl.pca(srv_2dpi_adata)

sc.tl.pca(srv_3dpi_adata)

from leidenalg.Optimiser import log
sc.tl.pca(mock_adata, svd_solver='arpack')
sc.pl.pca_variance_ratio(mock_adata, n_pcs=20,log=False)

sc.tl.pca(srv_1dpi_adata, svd_solver='arpack')
sc.pl.pca_variance_ratio(srv_1dpi_adata, n_pcs=20,log=False)

sc.tl.pca(srv_2dpi_adata, svd_solver='arpack')
sc.pl.pca_variance_ratio(srv_2dpi_adata, n_pcs=20,log=False)

sc.tl.pca(srv_3dpi_adata, svd_solver='arpack')
sc.pl.pca_variance_ratio(srv_3dpi_adata, n_pcs=20,log=False)

sc.pl.pca(mock_adata, color="condition", cmap="coolwarm")

sc.pl.pca(srv_1dpi_adata, color="condition", cmap="coolwarm")

sc.pl.pca(srv_2dpi_adata, color="condition", cmap="coolwarm")

sc.pl.pca(srv_3dpi_adata, color="condition", cmap="coolwarm")

"""## C. UMAP"""

#mock
sc.pp.neighbors(mock_adata) # Added this line to compute the neighborhood graph
sc.tl.umap(mock_adata)

#1dpi
sc.pp.neighbors(srv_1dpi_adata) # Added this line to compute the neighborhood graph
sc.tl.umap(srv_1dpi_adata)

#2dpi
sc.pp.neighbors(srv_2dpi_adata) # Added this line to compute the neighborhood graph
sc.tl.umap(srv_2dpi_adata)

#3dpi
sc.pp.neighbors(srv_3dpi_adata) # Added this line to compute the neighborhood graph
sc.tl.umap(srv_3dpi_adata)

sc.pl.umap(
    mock_adata,
    color=["condition", "ENO2", "ACE2"],
    size=10
)

sc.pl.umap(
    srv_1dpi_adata,
    color=["condition", "ENO2", "ACE2"],
    size=10
)

sc.pl.umap(
    srv_2dpi_adata,
    color=["condition", "ENO2", "ACE2"],
    size=10
)

sc.pl.umap(
    srv_3dpi_adata,
    color=["condition", "ENO2", "ACE2"],
    size=10
)

#mock
sc.tl.leiden(mock_adata, flavor="igraph", n_iterations=10, key_added="leiden_res0_02", resolution=0.25)

#1dpi
sc.tl.leiden(srv_1dpi_adata, flavor="igraph", n_iterations=10, key_added="leiden_res0_02", resolution=0.25)

#2dpi
sc.tl.leiden(srv_2dpi_adata, flavor="igraph", n_iterations=10, key_added="leiden_res0_02", resolution=0.25)

#3dpi
sc.tl.leiden(srv_3dpi_adata, flavor="igraph", n_iterations=10, key_added="leiden_res0_02", resolution=0.25)

#mock
sc.pl.umap(
    mock_adata,
    color=["leiden_res0_02"],
    size=10,
    title="mock"
)

#1dpi
sc.pl.umap(
    srv_1dpi_adata,
    color=["leiden_res0_02"],
    size=10,
    title="1dpi"
)

#2dpi
sc.pl.umap(
    srv_2dpi_adata,
    color=["leiden_res0_02"],
    size=10,
    title="2dpi"
)

#3dpi
sc.pl.umap(
    srv_3dpi_adata,
    color=["leiden_res0_02"],
    size=10,
    title="3dpi"
)

"""## D. Cell Annotation

#### 01. Decoupler and Panglao DB
"""

# Import decoupler for automatic mapping
import decoupler as dc

# Query Omnipath and get PanglaoDB
markers = dc.op.resource(name="PanglaoDB", organism="human")

markers.shape

markers.head()

markers['organ'].unique()

markers = markers[markers["organ"].isin(['Lungs', 'Epithelium', 'Immune system', 'Smooth Muscles'])]

markers.shape

import decoupler as dc
import pandas as pd

# 1. Re-load markers from the resource to ensure it's in the initial state
markers = dc.op.resource(name="PanglaoDB", organism="human")

# 2. Filter by organ
if 'organ' in markers.columns:
    markers = markers[markers["organ"].isin(['Lungs', 'Epithelium', 'Smooth muscle'])]
else:
    print("Warning: 'organ' column not found for organ filtering. Skipping.")

# 3. Remove duplicated entries using 'cell_type' and 'genesymbol'
# Check if columns exist before trying to use them for duplicated check
if 'cell_type' in markers.columns and 'genesymbol' in markers.columns:
    markers = markers[~markers.duplicated(["cell_type", "genesymbol"])]
else:
    print("Warning: 'cell_type' or 'genesymbol' column not found for duplicate removal. Skipping.")

# 4. Format because dc only accepts cell_type and genesymbol as 'source' and 'target'
# Check if columns exist before renaming
if 'cell_type' in markers.columns and 'genesymbol' in markers.columns:
    markers = markers.rename(columns={"cell_type": "source", "genesymbol": "target"})
else:
    print("Warning: 'cell_type' or 'genesymbol' column not found for renaming. Skipping.")

# 5. Select only 'source' and 'target' if they exist
if 'source' in markers.columns and 'target' in markers.columns:
    markers = markers[["source", "target"]]
else:
    print("Warning: 'source' or 'target' columns not found after processing. Final markers might be empty or incomplete.")

markers.head()

mock_adata.var_names
srv_1dpi_adata.var_names
srv_2dpi_adata.var_names
srv_3dpi_adata.var_names

#mock
dc.mt.ulm(data=mock_adata, net=markers, tmin=3)

#1dpi
dc.mt.ulm(data=srv_1dpi_adata, net=markers, tmin=3)

#2dpi
dc.mt.ulm(data=srv_2dpi_adata, net=markers, tmin=3)

#3dpi
dc.mt.ulm(data=srv_3dpi_adata, net=markers, tmin=3)



"""#### 02. Label clusters based on the strongest enrichment scores."""

#mock
score_mock = dc.pp.get_obsm(mock_adata, key="score_ulm")

#1dpi
score_1 = dc.pp.get_obsm(srv_1dpi_adata, key="score_ulm")

#2dpi
score_2 = dc.pp.get_obsm(srv_2dpi_adata, key="score_ulm")

#3dpi
score_3 = dc.pp.get_obsm(srv_3dpi_adata, key="score_ulm")

#Rank genes

#mock
mock_adata_gene_rank = dc.tl.rankby_group(score_mock, groupby="leiden_res0_02", reference="rest", method="t-test_overestim_var")
mock_adata_gene_rank = mock_adata_gene_rank[mock_adata_gene_rank["stat"] > 0]
mock_adata_gene_rank.head(5)

#1dpi
srv_1dpi_adata_gene_rank = dc.tl.rankby_group(score_1, groupby="leiden_res0_02", reference="rest", method="t-test_overestim_var")
srv_1dpi_adata_gene_rank = srv_1dpi_adata_gene_rank[srv_1dpi_adata_gene_rank["stat"] > 0]
srv_1dpi_adata_gene_rank.head(5)

#2dpi
srv_2dpi_adata_gene_rank = dc.tl.rankby_group(score_2, groupby="leiden_res0_02", reference="rest", method="t-test_overestim_var")
srv_2dpi_adata_gene_rank = srv_2dpi_adata_gene_rank[srv_2dpi_adata_gene_rank["stat"] > 0]
srv_2dpi_adata_gene_rank.head(5)

#3dpi
srv_3dpi_adata_gene_rank = dc.tl.rankby_group(score_3, groupby="leiden_res0_02", reference="rest", method="t-test_overestim_var")
srv_3dpi_adata_gene_rank = srv_3dpi_adata_gene_rank[srv_3dpi_adata_gene_rank["stat"] > 0]
srv_3dpi_adata_gene_rank.head(5)

#mock
top_cell_type_per_group_mock = mock_adata_gene_rank.groupby('group')['name'].apply(lambda x: x.head(1))
display(top_cell_type_per_group_mock.to_dict())

#1dpi
top_cell_type_per_group_1 = srv_1dpi_adata_gene_rank.groupby('group')['name'].apply(lambda x: x.head(1))
display(top_cell_type_per_group_1.to_dict())

#2dpi
top_cell_type_per_group_2 = srv_2dpi_adata_gene_rank.groupby('group')['name'].apply(lambda x: x.head(1))
display(top_cell_type_per_group_2.to_dict())

#3dpi
top_cell_type_per_group_3 = srv_3dpi_adata_gene_rank.groupby('group')['name'].apply(lambda x: x.head(1))
display(top_cell_type_per_group_3.to_dict())

#mock
sc.pl.umap(score_mock, color=["Basal cells","leiden_res0_02"], cmap="coolwarm")

#1dpi
sc.pl.umap(score_1, color=["Basal cells","leiden_res0_02"], cmap="coolwarm")

#2dpi
sc.pl.umap(score_2, color=["Basal cells","leiden_res0_02"], cmap="coolwarm")

#3dpi
sc.pl.umap(score_3, color=["Basal cells","leiden_res0_02"], cmap="coolwarm")

"""#### 03. Visualize annotated UMAP"""

sc.pl.umap(
    mock_adata,
    color=[ "leiden_res0_02", 'ENO2', 'ACE2'],
    ncols=8,
    title= 'mock'
)

sc.pl.umap(
    srv_1dpi_adata,
    color=[ "leiden_res0_02", 'ENO2', 'ACE2'],
    ncols=8,
    title= '1dpi'
)

sc.pl.umap(
    srv_2dpi_adata,
    color=[ "leiden_res0_02", 'ENO2', 'ACE2'],
    ncols=8,
    title= '2dpi'
)

sc.pl.umap(
    srv_3dpi_adata,
    color=[ "leiden_res0_02", 'ENO2', 'ACE2'],
    ncols=8,
    title= '3dpi'
)

sc.pl.umap(
    mock_adata,
    color=[ "leiden_res0_02", 'YWHAH', 'SQSTM1', 'RPL37A', 'NFKBIZ', 'NFKBIA'],
    ncols=8,
    title= 'mock'
)

sc.pl.umap(
    srv_1dpi_adata,
    color=[ "leiden_res0_02", 'YWHAH', 'SQSTM1', 'RPL37A', 'NFKBIZ', 'NFKBIA'],
    ncols=8,
    title= '1dpi'
)

sc.pl.umap(
    srv_2dpi_adata,
    color=[ "leiden_res0_02", 'YWHAH', 'SQSTM1', 'RPL37A', 'NFKBIZ','NFKBIA' ],
    ncols=8,
    title= '2dpi'
)

sc.pl.umap(
    srv_3dpi_adata,
    color=[ "leiden_res0_02", 'YWHAH', 'SQSTM1', 'RPL37A', 'NFKBIZ', 'NFKBIA'],
    ncols=8,
    title= '3dpi'
)

#mock
dict_ann_mock_raw = mock_adata_gene_rank[mock_adata_gene_rank["stat"] > 0].groupby("group").head().set_index("group")["name"].to_dict()
dict_ann_mock = {k: f"{v} ({k})" for k, v in dict_ann_mock_raw.items()}
display(dict_ann_mock)

#1dpi
dict_ann_1dpi_raw = srv_1dpi_adata_gene_rank[srv_1dpi_adata_gene_rank["stat"] > 0].groupby("group").head().set_index("group")["name"].to_dict()
dict_ann_1dpi = {k: f"{v} ({k})" for k, v in dict_ann_1dpi_raw.items()}
display(dict_ann_1dpi)

#2dpi
dict_ann_2dpi_raw = srv_2dpi_adata_gene_rank[srv_2dpi_adata_gene_rank["stat"] > 0].groupby("group").head().set_index("group")["name"].to_dict()
dict_ann_2dpi = {k: f"{v} ({k})" for k, v in dict_ann_2dpi_raw.items()}
display(dict_ann_2dpi)

#3dpi
dict_ann_3dpi_raw = srv_3dpi_adata_gene_rank[srv_3dpi_adata_gene_rank["stat"] > 0].groupby("group").head().set_index("group")["name"].to_dict()
dict_ann_3dpi = {k: f"{v} ({k})" for k, v in dict_ann_3dpi_raw.items()}
display(dict_ann_3dpi)

#mock
mock_adata.obs["leiden_res0_02"] = mock_adata.obs["leiden_res0_02"].cat.rename_categories(dict_ann_mock)

#1dpi
srv_1dpi_adata.obs["leiden_res0_02"] = srv_1dpi_adata.obs["leiden_res0_02"].cat.rename_categories(dict_ann_1dpi)

#2dpi
srv_2dpi_adata.obs["leiden_res0_02"] = srv_2dpi_adata.obs["leiden_res0_02"].cat.rename_categories(dict_ann_2dpi)

#3dpi
srv_3dpi_adata.obs["leiden_res0_02"] = srv_3dpi_adata.obs["leiden_res0_02"].cat.rename_categories(dict_ann_3dpi)

print("Performing differential expression analysis for mock_adata...")
sc.tl.rank_genes_groups(mock_adata, groupby='leiden_res0_02', method='wilcoxon', rankby_abs=True, key_added='rank_genes_groups_mock')
print("Done with mock_adata.\nPerforming differential expression analysis for srv_1dpi_adata...")
sc.tl.rank_genes_groups(srv_1dpi_adata, groupby='leiden_res0_02', method='wilcoxon', rankby_abs=True, key_added='rank_genes_groups_1dpi')
print("Done with srv_1dpi_adata.\nPerforming differential expression analysis for srv_2dpi_adata...")
sc.tl.rank_genes_groups(srv_2dpi_adata, groupby='leiden_res0_02', method='wilcoxon', rankby_abs=True, key_added='rank_genes_groups_2dpi')
print("Done with srv_2dpi_adata.\nPerforming differential expression analysis for srv_3dpi_adata...")
sc.tl.rank_genes_groups(srv_3dpi_adata, groupby='leiden_res0_02', method='wilcoxon', rankby_abs=True, key_added='rank_genes_groups_3dpi')
print("Done with srv_3dpi_adata.")

adata_combined = ad.concat([mock_adata, srv_1dpi_adata, srv_2dpi_adata, srv_3dpi_adata])

# Create a combined 'condition_cell_type' column for dot plot grouping
adata_combined.obs['condition_cell_type'] = adata_combined.obs['condition'].astype(str) + '_' + adata_combined.obs['leiden_res0_02'].astype(str)

print("Combined AnnData object created and 'condition_cell_type' column added.")
print(adata_combined.obs['condition_cell_type'].value_counts().head())

#Visualisation of cell annotation

#mock
sc.pl.umap(
    mock_adata,
    color=["leiden_res0_02"],
    ncols=3,
    title='Mock - Marker Gene Expression',
    size=5
)

#1dpi
sc.pl.umap(
    srv_1dpi_adata,
    color=["leiden_res0_02"],
    ncols=3,
    title='1dpi - Marker Gene Expression',
    size=5
)

#2dpi
sc.pl.umap(
    srv_2dpi_adata,
    color=["leiden_res0_02"],
    ncols=3,
    title='2dpi - Marker Gene Expression',
    size=5
)

#3dpi
sc.pl.umap(
    srv_3dpi_adata,
    color=["leiden_res0_02"],
    ncols=3,
    title='3dpi - Marker Gene Expression',
    size=5
)

"""#### 03. Check cell-type composition per infection stage."""

adata.obs['condition'].value_counts()

"""##### Data Analysis Key Findings
A total of 485 unique marker genes were extracted from the markers DataFrame, serving as a basis for cell type annotation. Differential expression analysis was successfully performed for mock_adata, srv_1dpi_adata, srv_2dpi_adata, and srv_3dpi_adata using the Wilcoxon method, identifying cluster-specific significant genes for each condition. UMAP visualizations were generated for all four conditions (mock, 1dpi, 2dpi, 3dpi), effectively displaying the distribution and expression levels of selected marker genes like KRT5, CD14, ACTA2, SFTPC, and SCGB1A1. The dot plot, combining data from all conditions and cell types, was successfully created to compare marker expression patterns and statistical significance across all groups, providing an integrated view of  expression changes.

##Trajectory Inference
####It is an attempt to understand how cells transition from one type to another (like stem → mature)?
"""

#Trajectory analysis
sc.tl.draw_graph(mock_adata)
sc.tl.draw_graph(srv_1dpi_adata)
sc.tl.draw_graph(srv_2dpi_adata)
sc.tl.draw_graph(srv_3dpi_adata)

# mock
plt.rcParams["figure.figsize"] = (4,4)
sc.pl.draw_graph(mock_adata, color='leiden_res0_02', size = 16)

#1dpi
plt.rcParams["figure.figsize"] = (4,4)
sc.pl.draw_graph(srv_1dpi_adata, color='leiden_res0_02', size = 16)

#2dpi
plt.rcParams["figure.figsize"] = (4,4)
sc.pl.draw_graph(srv_2dpi_adata, color='leiden_res0_02', size = 16)

#3dpi
plt.rcParams["figure.figsize"] = (4,4)
sc.pl.draw_graph(srv_3dpi_adata, color='leiden_res0_02', size = 16)

#PAGA mock to 3dpi

sc.tl.paga(mock_adata, groups='leiden_res0_02')
sc.tl.paga(srv_1dpi_adata, groups='leiden_res0_02')
sc.tl.paga(srv_2dpi_adata, groups='leiden_res0_02')
sc.tl.paga(srv_3dpi_adata, groups='leiden_res0_02')

sc.pl.paga(mock_adata, color=['leiden_res0_02'])
sc.pl.paga(srv_1dpi_adata, color=['leiden_res0_02'])
sc.pl.paga(srv_2dpi_adata, color=['leiden_res0_02'])
sc.pl.paga(srv_3dpi_adata, color=['leiden_res0_02'])

#mock
plt.rcParams["figure.figsize"] = (5,4)
sc.pl.paga_compare(mock_adata, threshold=0.03, frameon=True, edges=True, size = 16)

#1dpi
plt.rcParams["figure.figsize"] = (5,4)
sc.pl.paga_compare(srv_1dpi_adata, threshold=0.03, frameon=True, edges=True, size = 16)

#2dpi
plt.rcParams["figure.figsize"] = (5,4)
sc.pl.paga_compare(srv_2dpi_adata, threshold=0.03, frameon=True, edges=True, size = 16)

#3dpi
plt.rcParams["figure.figsize"] = (5,4)
sc.pl.paga_compare(srv_3dpi_adata, threshold=0.03, frameon=True, edges=True, size = 16)

# Calculate diffusion pseudotime (DPT)

# mock
# As an example, let's select a cell from the first cluster (cluster '0') as the root.
# You might need to adjust this based on your biological knowledge.
root_cluster_mock = 'Ciliated cells (4)' # Corrected: based on dict_ann_mock, Ciliated cells is cluster 4
if root_cluster_mock in mock_adata.obs['leiden_res0_02'].cat.categories:
    root_cell_idx_mock = mock_adata.obs['leiden_res0_02'] == root_cluster_mock
    if np.any(root_cell_idx_mock):
        mock_adata.uns['iroot'] = np.flatnonzero(root_cell_idx_mock)[0] # Set iroot
        sc.tl.dpt(mock_adata) # Call dpt without the 'root' argument
    else:
        print(f"Warning: No cells found in cluster {root_cluster_mock} for mock_adata. Skipping DPT calculation.")
else:
    print(f"Warning: Cluster {root_cluster_mock} not found in mock_adata. Skipping DPT calculation.")

# 1dpi
root_cluster_1dpi = 'Myofibroblasts (0)' # Replace with the actual name of your root cluster if '0' is not correct
if root_cluster_1dpi in srv_1dpi_adata.obs['leiden_res0_02'].cat.categories:
    root_cell_idx_1dpi = srv_1dpi_adata.obs['leiden_res0_02'] == root_cluster_1dpi
    if np.any(root_cell_idx_1dpi):
        srv_1dpi_adata.uns['iroot'] = np.flatnonzero(root_cell_idx_1dpi)[0] # Set iroot
        sc.tl.dpt(srv_1dpi_adata) # Call dpt without the 'root' argument
    else:
        print(f"Warning: No cells found in cluster {root_cluster_1dpi} for srv_1dpi_adata. Skipping DPT calculation.")
else:
    print(f"Warning: Cluster {root_cluster_1dpi} not found in srv_1dpi_adata. Skipping DPT calculation.")

# 2dpi
root_cluster_2dpi = 'Mesothelial cells (0)' # Replace with the actual name of your root cluster if '0' is not correct
if root_cluster_2dpi in srv_2dpi_adata.obs['leiden_res0_02'].cat.categories:
    root_cell_idx_2dpi = srv_2dpi_adata.obs['leiden_res0_02'] == root_cluster_2dpi
    if np.any(root_cell_idx_2dpi):
        srv_2dpi_adata.uns['iroot'] = np.flatnonzero(root_cell_idx_2dpi)[0] # Set iroot
        sc.tl.dpt(srv_2dpi_adata) # Call dpt without the 'root' argument
    else:
        print(f"Warning: No cells found in cluster {root_cluster_2dpi} for srv_2dpi_adata. Skipping DPT calculation.")
else:
    print(f"Warning: Cluster {root_cluster_2dpi} not found in srv_2dpi_adata. Skipping DPT calculation.")

# 3dpi
root_cluster_3dpi = 'Airway goblet cells (0)' # Replace with the actual name of your root cluster if '0' is not correct
if root_cluster_3dpi in srv_3dpi_adata.obs['leiden_res0_02'].cat.categories:
    root_cell_idx_3dpi = srv_3dpi_adata.obs['leiden_res0_02'] == root_cluster_3dpi
    if np.any(root_cell_idx_3dpi):
        srv_3dpi_adata.uns['iroot'] = np.flatnonzero(root_cell_idx_3dpi)[0] # Set iroot
        sc.tl.dpt(srv_3dpi_adata) # Call dpt without the 'root' argument
    else:
        print(f"Warning: No cells found in cluster {root_cluster_3dpi} for srv_3dpi_adata. Skipping DPT calculation.")
else:
    print(f"Warning: Cluster {root_cluster_3dpi} not found in srv_3dpi_adata. Skipping DPT calculation.")

# Now plot with dpt_pseudotime
sc.pl.draw_graph(mock_adata, color=['dpt_pseudotime', 'leiden_res0_02'], legend_loc='on data', size = 24)
sc.pl.draw_graph(srv_1dpi_adata, color=['dpt_pseudotime', 'leiden_res0_02'], legend_loc='on data', size = 24)
sc.pl.draw_graph(srv_2dpi_adata, color=['dpt_pseudotime', 'leiden_res0_02'], legend_loc='on data', size = 24)
sc.pl.draw_graph(srv_3dpi_adata, color=['dpt_pseudotime', 'leiden_res0_02'], legend_loc='on data', size = 24)

